name: Publish Npm Package

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  Publish:
    name: Publish
    runs-on: ubuntu-24.04
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Check out repo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24.6.0'
          registry-url: 'https://registry.npmjs.org/'

      - name: Update NPM Version
        run: |
          npm --version
          # npm install -g npm@11.5.2 # 11.5.1 or later is required for OIDC
          # npm --version

      # - name: Publish to npm
      #   run: npm publish --access public

      # - name: Publish to npm
      #   run: |
      #     npm --version
      #     npm publish --access public --provenance --registry=https://registry.npmjs.org/