name: Hello World

on:
    push:
        branches:
            - main
    pull_request:

jobs:
    hello-world:
        environment: testing-approvals
        runs-on: ubuntu-latest
        steps:
            - name: Print Hello World
              run: echo "Hello, World!"
